### ISSUE TITLE
`Javascript heap out of memory`

### ISSUE THREAD

**Issue by willviles** [ember-fastboot/fastboot-app-server#62] opened 2017-08-22 10:49 UTC
Our production app using Fastboot App Server (w/ ember-cli-fastboot v1.0.2) is hitting `JavaScript heap out of memory`, requiring us to restart our Beanstalk node processes. 

Has anyone else encountered this problem?

We could just put pm2 in front of our Fastboot app server and get it to restart on max mem, for example: 
```
pm2 start /app/fastboot-server.js --no-daemon -i 0 --max-memory-restart 100M
``` 
...but that’s just a temporary bandage.

What are the possible causes for this issue and has anyone got any tips on the best way to discover memory leak issues in a Fastboot environment?

Also I’m considering whether something like [node-memwatch](https://github.com/lloyd/node-memwatch) could be perhaps utilised in Ember CLI to detect memory leaks in application code?

**Comment by kratiahuja** [comment] 2017-08-22 18:52
It would be great if you could do a minimal reproduction that exhibits the problem and then I can take a look at it. It could also most likely means your app is leaking something.

**Comment by devdemi** [comment] 2017-10-30 15:34
I have same problem. I have the docker container with Fastboot App Server. My server.js:
```javascript
'use strict';

const FastBootAppServer = require('fastboot-app-server');

let server = new FastBootAppServer({
    distPath: 'dist',
    gzip: true, // Optional - Enables gzip compression.
    host: '0.0.0.0', // Optional - Sets the host the server listens on.
    port: 4200 // Optional - Sets the port the server listens on (defaults to the PORT env var or 3000).
});

server.start();
```
I attached Memory Utilization graph.
![a2b3d306b0](https://user-images.githubusercontent.com/890372/32179509-3d90cf14-bd98-11e7-8965-8d0330719be4.png)

**Comment by willviles** [comment] 2017-10-30 15:47
So, I can confirm all of our memory leaks came from application code. We debugged it following [these examples](https://github.com/ember-best-practices/memory-leak-examples), using a mix of Keymetrics on our pm2 process & Chrome debugger directly debugging from our Fastboot app server port.

The biggest culprits were from adding mutable instances of arrays or objects directly to class prototypes:

**BAD:**
```js
Ember.Component.extend({
  prop: ['one', 'two', 'three'],
  prop2: {
    foo: true,
    bar: false
  }
});
```

**GOOD**
```js
Ember.Component.extend({
  init() {
    this.super(...arguments);
    setProperties(this, {
      prop: ['one', 'two', 'three'],
      prop2: {
        foo: true,
        bar: false
      }
    });
  }
});
```

Also watch out for cases of event listeners or Ember Concurrency tasks not being swept up on `willDestroy`/`willDestroyElement` hooks.

**Comment by kratiahuja** [comment] 2017-10-30 15:50
Thank you @willviles ! Going to close this.

**Closed by kratiahuja** 2017-10-30 15:50 UTC

**Comment by Redsandro** [comment] 2018-05-31 18:58
@willviles can you explain why this helps? Do you know of a resource that explains this in more detail?

Because on Embers' own documentation, they don't do this.

![image](https://user-images.githubusercontent.com/1702193/40802270-6890c406-6515-11e8-83c4-61e6dd19d946.png)

Are they teaching us wrong?

**Comment by Redsandro** [comment] 2018-06-01 13:07
@willviles thank you, much appreciated. :+1: 

The rule will come in handy, although Ember 2.x projects still default to `jshint` in stead of `eslint`. But I'm sure I can port my configuration.

> Adding mutable arrays directly to the class leaks the state into new instances of the class created thereafter

I don't really understand this, as according to my limited intuition, the Ember function will `export` the _result_ from the _extension_, but I know you're correct, as the proof is in my crashing server. :grimacing:
